In [1]:
import numpy as np
import time
import sys

In [2]:
### Python Array Size (Memory)

l = range(1000)
print(sys.getsizeof(5)*len(l))

28000


In [3]:
### Numpy Size

array = np.arange(1000)
print(array.size*array.itemsize)

4000


In [4]:
SIZE = 100000

In [5]:
l1 = range(SIZE)
l2 = range(SIZE)

In [6]:
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

In [7]:
## python list

start = time.time()
result = [(x+y) for x,y in zip(l1,l2)]
print("python list took: ", (time.time()-start)*1000)

python list took:  46.059608459472656


In [8]:
## numpy array

start = time.time()
result = a1+a2
print("numpy took: ", (time.time()-start)*1000)

numpy took:  6.238460540771484


In [9]:
## Add, Multipy, Division

a1 = np.array([1,2,3])
a2 = np.array([4,5,6])

print(a1 + a2)
print(a2 - a1)
print(a1 * a2)
print(a1 / a2)

[5 7 9]
[3 3 3]
[ 4 10 18]
[0.25 0.4  0.5 ]
