In [1]:
import numpy as np

In [5]:
a = np.array([5,6,9])
a[0]

5

In [8]:
### dimension

a.ndim

2

In [9]:
a = np.array([[1,2],[3,4],[5,6]])
a.ndim

2

In [13]:
# integer 

print(a.itemsize)
a.dtype

4


dtype('int32')

In [14]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.float64)
a.itemsize

8

In [15]:
a

array([[1., 2.],
       [3., 4.],
       [5., 6.]])

In [16]:
# size

a.size

6

In [17]:
# shape

a.shape

(3, 2)

In [19]:
a = np.array([[1,2],[3,4],[5,6]], dtype = np.complex)
a

array([[1.+0.j, 2.+0.j],
       [3.+0.j, 4.+0.j],
       [5.+0.j, 6.+0.j]])

In [20]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [21]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [26]:
list = range(5)
print(list)

print(list[2])
print(list[0])

range(0, 5)
2
0


In [27]:
np.arange(1,5)

array([1, 2, 3, 4])

In [28]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [30]:
# linear sequence of number
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [31]:
# reshape

In [32]:
a = np.array([[1,2],[3,4],[5,6]])
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [34]:
a.shape

(3, 2)

In [37]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
a.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [40]:
a.ravel()

array([1, 2, 3, 4, 5, 6])

In [41]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [42]:
a.min()

1

In [43]:
a.max()

6

In [44]:
a.sum()

21

In [49]:
# column

a.sum(axis=0)

array([ 9, 12])

In [48]:
# row

a.sum(axis=1)

array([ 3,  7, 11])